### ISSUE TITLE
Retire this repo?

### ISSUE THREAD

**Issue by BillWSY** [CogRob/bibtex#1]
There is a newly created publications repo. Should we remove this repo so we only have a single source of truth?

**Comment by ruffsl** [comment]
This is what the website points today.
We'll have to add an automated method to generate a single .bib file that both papercite plugin and bibbase and pull from, as they can only use one url resource. I'd also like to add a bibtex linter, such as https://github.com/FlamingTempura/bibtex-tidy to validate PRs, and to organize entries for reading.

Once the above is done, we can delete this repo after we've migrated the site to https://github.com/CogRob/publications. It'll also have to be change to public.

**Comment by ruffsl** [comment]
Done!
